// hw3-vue/src/pages/priorities/Priorities.vue
<template>
  <div class="mt-8">
    <h1 class="text-xl font-semibold mb-4 ml-5">List of Your Priorities</h1>
    <div class="overflow-x-auto">
      <table class="min-w-full bg-white shadow-md rounded-lg">
        <thead class="bg-gray-800 text-white">
          <tr>
            <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Priority Name</th>
            <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Priority Sort</th>
            <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Sync Date</th>
            <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Actions</th>
          </tr>
        </thead>
        <tbody class="text-gray-700">
          <tr v-for="(item, index) in priorities" :key="item.id"
              :class="{'bg-gray-100': index % 2 === 0, 'bg-white': index % 2 !== 0}">
            <td class="text-left py-3 px-4">{{ item.priorityName }}</td>
            <td class="text-left py-3 px-4">{{ item.prioritySort }}</td>
            <td class="text-left py-3 px-4">{{ formatDate(item.syncDt) }}</td>
            <td class="text-left py-3 px-4">
              <router-link :to="`/priorities/edit/${item.id}`" class="text-blue-500 hover:text-blue-600">Edit</router-link> |
              <router-link :to="`/priorities/details/${item.id}`" class="text-blue-500 hover:text-blue-600">Details</router-link> |
              <router-link :to="`/priorities/delete/${item.id}`" class="text-red-500 hover:text-red-600">Delete</router-link>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
  

<script setup lang="ts">

  import { ref, onMounted } from 'vue';
  import GetService from '@/services/CRUD/GetService';
  import formatDate from '@/utils/FormatDate';
  import type { IPriority } from '@/domain/IPriority';
  import { state } from '@/state/AppState';
  
      let priorities = ref<IPriority[]>([]);
      const isLoading = ref(true);
      const userInfo = state.userInfo;
  
      const loadData = async () => {
        if (!userInfo.token) { 
          console.error("User token is not available.");
          return;
        }
  
        try {
          const response = await GetService.getPriority(userInfo.token); 
          if (response.data) {
            console.log(userInfo);
            priorities.value = response.data;
          } else {
            console.error("Failed to retrieve data", response);
          }
        } catch (e) {
          console.error("Failed to load priorities:", e);
        } finally {
          isLoading.value = false;
          console.log(priorities.value);
        }
      };
  
      onMounted(() => {
        loadData();
      });
    
</script>

// hw3-react/src/app/todo/priorities/page.tsx
"use client"

import { IPriority } from "@/domain/IPriority";
import { AppContext } from "@/state/AppContext";
import { useContext, useEffect, useState } from "react";
import formatDate from "../FormatDate";
import Link from "next/link";
import GetService from "@/services/CRUD/GetService";

export default function Priorities() {
    const [isLoading, setIsLoading] = useState(true);
    const [priority, setPriority] = useState<IPriority[]>([]);
    const { userInfo } = useContext(AppContext)!;


    const loadData = async () => {
        try {
            const response = await GetService.getPriority(userInfo!.token)
            if (response.data) {
                setPriority(response.data);
            }
            setIsLoading(false);
        }
        catch (e) {
            console.log(e);
        }
    };

    useEffect(() => { loadData() }, []);

    if (isLoading) return (<h1>Priorities - LOADING</h1>);

    return (
        <>
            <h1>Priorities</h1>

            <p>
                <Link href="/todo/priorities/create">Create new</Link>
            </p>
            <table className="table">
                <thead>
                    <tr>
                        <th>
                            PriorityName
                        </th>
                        <th>
                            PrioritySort
                        </th>
                        <th>
                            SyncDt
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {priority.map((priority) =>

                        <tr key={priority.id}>
                            <td>
                                {priority.priorityName}
                            </td>
                            <td>
                                {priority.prioritySort}
                            </td>
                            <td>
                                {formatDate(priority.syncDt)}
                            </td>
                            <td>
                                <Link href={`/todo/priorities/edit/${priority.id}`}>Edit</Link> |
                                <Link href={`/todo/priorities/details/${priority.id}`}>Details</Link> |
                                <Link href={`/todo/priorities/delete/${priority.id}`}>Delete</Link>
                            </td>
                        </tr>
                    )}
                </tbody>
            </table>
        </>
    );
}
